# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Rust Security audit

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_call: {}
  workflow_dispatch:

permissions: {}

concurrency:
  group: audit-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read # Required to checkout the repository

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install cargo-audit
        uses: taiki-e/install-action@d6e286fa45544157a02d45a43742857ebbc25d12 # v2.68.16
        with:
          tool: cargo-audit

      - name: Run audit
        run: cargo audit
